# Generated by Django 4.2.6 on 2024-06-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_events', '0003_alter_event_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bout',
        ),
    ]
