# Generated by Django 4.2.4 on 2023-09-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufc_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RankingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('champion', models.BooleanField(default=False)),
                ('interm_champion', models.BooleanField(default=False)),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_to_ranking', to='ufc_base.fighterprofile')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_to_fighter', to='ufc_rankings.ranking')),
            ],
            options={
                'ordering': ['rank_number'],
            },
        ),
        migrations.AddField(
            model_name='ranking',
            name='ranking_spot',
            field=models.ManyToManyField(through='ufc_rankings.RankingSpot', to='ufc_base.fighterprofile'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='weight_division',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_weight', to='ufc_base.weightdivision'),
        ),
    ]
