# Generated by Django 4.2.4 on 2023-10-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingspot',
            name='rank_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
