# Generated by Django 4.2.4 on 2023-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_rankings', '0002_alter_rankingspot_rank_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='ranking_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
