# Generated by Django 4.2.4 on 2023-10-25 15:47

import apps.ufc_feed.models
import ckeditor.fields
from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, scale=1, size=[1920, 1080], upload_to=apps.ufc_feed.models.cover_loc)),
                ('title', models.CharField(max_length=155)),
                ('description', ckeditor.fields.RichTextField()),
                ('demo', models.FileField(upload_to=apps.ufc_feed.models.demo_loc)),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
