# Generated by Django 4.2.6 on 2024-06-02 16:32

import apps.ufc_feed.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='demo',
            field=models.FileField(upload_to=apps.ufc_feed.models.demo_loc, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
