# Generated by Django 4.2.4 on 2023-09-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('number_of_rounds', models.PositiveIntegerField()),
                ('t_round', models.FloatField()),
                ('status', models.CharField(choices=[('CE', 'CANCELLED'), ('UP', 'UPCOMING'), ('FT', 'FOUGHT')], max_length=155)),
                ('result', models.CharField(blank=True, choices=[('NC', 'NOCONTEST'), ('DW', 'DRAW')], max_length=155, null=True)),
                ('method', models.CharField(blank=True, choices=[('SM', 'SUBMISSION'), ('KO', 'KNOCKOUT'), ('TKO', 'TECHNICAL KNOCKOUT')], max_length=155, null=True)),
                ('early_prelimns', models.BooleanField(default=False)),
                ('prelimns', models.BooleanField(default=False)),
                ('main_card', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FighterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=155)),
                ('nickname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('native_city', models.CharField(max_length=155)),
                ('f_photo', models.ImageField(upload_to='')),
                ('c_photo', models.ImageField(upload_to='')),
                ('age', models.PositiveIntegerField()),
                ('reach', models.FloatField()),
                ('height', models.FloatField()),
                ('leg_reach', models.FloatField()),
                ('weight', models.FloatField()),
                ('number_of_fights', models.PositiveIntegerField()),
                ('victories', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('draws', models.PositiveIntegerField()),
                ('no_contest', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FighterStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FighterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_weight', models.FloatField()),
                ('max_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corner', models.CharField(blank=True, choices=[('RC', 'Red corner'), ('BC', 'Blue corner')], max_length=155)),
                ('loss', models.BooleanField(default=False)),
                ('victory', models.BooleanField(default=False)),
                ('fight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fight_to_fighter', to='ufc_base.fight')),
                ('fighter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fighter_to_fight', to='ufc_base.fighterprofile')),
            ],
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='fighter_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ufc_base.fightertag'),
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ufc_base.fighterstatus'),
        ),
        migrations.AddField(
            model_name='fighterprofile',
            name='weight_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ufc_base.weightdivision'),
        ),
        migrations.AddField(
            model_name='fight',
            name='fighter_participation',
            field=models.ManyToManyField(through='ufc_base.Participation', to='ufc_base.fighterprofile'),
        ),
    ]
