# Generated by Django 4.2.4 on 2023-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fighter_partipation',
            field=models.ManyToManyField(related_name='fight_participation', through='ufc_base.Participation', to='ufc_base.fighterprofile'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='corner',
            field=models.CharField(choices=[('RC', 'Red corner'), ('BC', 'Blue corner')], max_length=155),
        ),
    ]
