# Generated by Django 4.2.4 on 2023-09-07 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighterprofile',
            name='fighter_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fighterprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
