# Generated by Django 4.2.4 on 2023-08-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0002_alter_fight_fighter_partipation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fight',
            old_name='fighter_partipation',
            new_name='fighter_participation',
        ),
    ]
