# Generated by Django 4.2.4 on 2023-09-02 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0003_rename_fighter_partipation_fight_fighter_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='corner',
            field=models.CharField(blank=True, choices=[('RC', 'Red corner'), ('BC', 'Blue corner')], max_length=155),
        ),
        migrations.AlterField(
            model_name='participation',
            name='fighter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corner_atts', to='ufc_base.fighterprofile'),
        ),
    ]
