# Generated by Django 4.2.4 on 2023-09-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0004_alter_participation_corner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fighter_participation',
            field=models.ManyToManyField(related_name='fights', through='ufc_base.Participation', to='ufc_base.fighterprofile'),
        ),
    ]
