# Generated by Django 4.2.4 on 2023-09-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0006_alter_fight_card_alter_fight_tier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fight',
            options={'ordering': ['card']},
        ),
        migrations.AlterField(
            model_name='fight',
            name='card',
            field=models.CharField(blank=True, choices=[('MAIN CARD', 0), ('PRELIMS', 1), ('EARLY PRELIMS', 2)], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='fight',
            name='tier',
            field=models.CharField(blank=True, choices=[('fight-0', 0), ('fight-1', 1), ('fight-2', 2), ('fight-3', 3), ('fight-4', 4)], max_length=155, null=True),
        ),
    ]
