# Generated by Django 4.2.4 on 2023-10-12 16:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0010_alter_fight_card_alter_fight_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighterprofile',
            name='p_photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, scale=1, size=[329, 500], upload_to=''),
        ),
    ]
