# Generated by Django 4.2.4 on 2023-10-12 17:59

import apps.ufc_base.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ufc_base', '0012_remove_fighterprofile_p_photo_alter_fight_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighterprofile',
            name='f_photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, scale=1, size=[190, 588], upload_to=apps.ufc_base.models.f_photo),
        ),
    ]
